targets:
  $default:
    sources:
      - lib/** 
      - lib/swagger/** 
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/swagger/"
          output_folder: "lib/generated/"
